// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: oauth/oauth.proto

package oauth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OAuthRouteClient is the client API for OAuthRoute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OAuthRouteClient interface {
	VerifyUserToken(ctx context.Context, in *VerifyTokenParams, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
	VerifyWSToken(ctx context.Context, in *VerifyTokenParams, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
}

type oAuthRouteClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthRouteClient(cc grpc.ClientConnInterface) OAuthRouteClient {
	return &oAuthRouteClient{cc}
}

func (c *oAuthRouteClient) VerifyUserToken(ctx context.Context, in *VerifyTokenParams, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/oauth.OAuthRoute/VerifyUserToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthRouteClient) VerifyWSToken(ctx context.Context, in *VerifyTokenParams, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/oauth.OAuthRoute/VerifyWSToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthRouteServer is the server API for OAuthRoute service.
// All implementations must embed UnimplementedOAuthRouteServer
// for forward compatibility
type OAuthRouteServer interface {
	VerifyUserToken(context.Context, *VerifyTokenParams) (*VerifyTokenResponse, error)
	VerifyWSToken(context.Context, *VerifyTokenParams) (*VerifyTokenResponse, error)
	mustEmbedUnimplementedOAuthRouteServer()
}

// UnimplementedOAuthRouteServer must be embedded to have forward compatible implementations.
type UnimplementedOAuthRouteServer struct {
}

func (UnimplementedOAuthRouteServer) VerifyUserToken(context.Context, *VerifyTokenParams) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUserToken not implemented")
}
func (UnimplementedOAuthRouteServer) VerifyWSToken(context.Context, *VerifyTokenParams) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyWSToken not implemented")
}
func (UnimplementedOAuthRouteServer) mustEmbedUnimplementedOAuthRouteServer() {}

// UnsafeOAuthRouteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthRouteServer will
// result in compilation errors.
type UnsafeOAuthRouteServer interface {
	mustEmbedUnimplementedOAuthRouteServer()
}

func RegisterOAuthRouteServer(s grpc.ServiceRegistrar, srv OAuthRouteServer) {
	s.RegisterService(&OAuthRoute_ServiceDesc, srv)
}

func _OAuthRoute_VerifyUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthRouteServer).VerifyUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.OAuthRoute/VerifyUserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthRouteServer).VerifyUserToken(ctx, req.(*VerifyTokenParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthRoute_VerifyWSToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthRouteServer).VerifyWSToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.OAuthRoute/VerifyWSToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthRouteServer).VerifyWSToken(ctx, req.(*VerifyTokenParams))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthRoute_ServiceDesc is the grpc.ServiceDesc for OAuthRoute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthRoute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oauth.OAuthRoute",
	HandlerType: (*OAuthRouteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyUserToken",
			Handler:    _OAuthRoute_VerifyUserToken_Handler,
		},
		{
			MethodName: "VerifyWSToken",
			Handler:    _OAuthRoute_VerifyWSToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth/oauth.proto",
}
